name: 'Spec compliance report'
description: 'Generate compliance report and publish on Github pages'

inputs:
  report-script:
    description: 'Path to script that generates a compliance report'
    required: true
  h3-dir:
    description: 'Path to the directory where h3 is cloned'
    required: false
    default: ${{ github.workspace }}

runs:
  using: "composite"
  steps:
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Cache builds
      uses: camshaft/rust-cache@v1

    - name: Install Duvet w/ caching
      uses: camshaft/install@v1
      with:
        crate: duvet

    - name: Set variables
      shell: bash
      run: |
        echo "SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

    # create gh-pages as an orphan branch if branch does not exist
    - name: Checkout gh-pages
      shell: bash
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"

        if git ls-remote --exit-code --heads origin gh-pages; then
          cp -r .duvet .github ci h3 target
          git switch gh-pages
          cp -r target/.duvet target/.github target/ci target/h3 .
        else
          git checkout --orphan gh-pages
          git reset
        fi

    - name: Generate report
      working-directory: ${{ inputs.h3-dir }}
      shell: bash
      run: |
        ${{ inputs.report-script }}

    # commit only when there are changes
    - name: Commit report changes
      working-directory: ${{ inputs.h3-dir }}
      shell: bash
      run: |
        cp .duvet/reports/* ci/compliance/
        git add ci/compliance/*.html
        git diff --staged --quiet || \
        git commit -m "${{ github.triggering_actor }}-${SHA}-${{ github.job }}#${{ github.run_number }}"

    # publish report only when pushing to master
    - name: Push to gh-pages
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@v1
      with:
        github_token: ${{ github.token }}
        branch: gh-pages
        force: true
