name: 'Spec compliance'
description: 'Use Duvet to generate spec compliance report'

inputs:
  extract-script:
    description: 'Path to script that extracts compliance checks'
    required: true
  report-script:
    description: 'Path to script that generates a Duvet report'
    required: true
  dir:
    description: 'Path to the directory where h3 is cloned'
    default: ${{ github.workspace }}
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions-rs/toolchain@v1
      id: toolchain
      with:
        toolchain: stable
        override: true

    - uses: camshaft/rust-cache@v1

    - name: Purge & prep
      working-directory: ${{ inputs.dir }}
      run: |
        rm -f target/release/duvet
        export latest_version="$(cargo search duvet | grep -Eo '^duvet *= *"[0-9\.]+"' | grep -Eo '[0-9\.]+')"
        echo "DUVET_LV=${latest_version}" >> $GITHUB_ENV
      shell: bash

    - name: Cache & restore duvet
      uses: actions/cache@v3
      continue-on-error: true
      with:
        path: ${{ inputs.dir }}/target/release/duvet
        key: ${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-${{ github.job }}-${{ hashFiles(format('{0}/Cargo.toml', inputs.dir)) }}-duvet@${{ env.DUVET_LV }}

    - name: Install duvet
      working-directory: ${{ inputs.dir }}
      run: |
        if [ ! -x target/release/duvet ]; then
          cargo install duvet
          mkdir -p target/release
          cp $HOME/.cargo/bin/duvet target/release/duvet
        fi

        echo "${{ inputs.dir }}/target/release" >> $GITHUB_PATH
      shell: bash

    - name: Checkout gh-pages
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

        if git ls-remote --exit-code --heads origin gh-pages; then
          cp -r .github ci h3 tests target
          git switch gh-pages
          cp -r target/.github target/ci target/h3 target/tests .
        else
          git checkout --orphan gh-pages
          git reset
        fi
      shell: bash

    - name: Generate duvet report
      working-directory: ${{ inputs.dir }}
      run: |
        ${{ inputs.extract-script }}
        ${{ inputs.report-script }} ${{ github.sha }}
      shell: bash

    - name: Commit
      working-directory: ${{ inputs.dir }}
      run: |
        git add ci/compliance/*.html
        git diff --staged --quiet || \
        git commit -m "${{ github.triggering_actor }}-${{ github.sha }}-${{ github.job }}#${{ github.run_number }}"
      shell: bash

    - name: Push to gh-pages
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ github.token }}
        branch: gh-pages
        force: true
