target = "https://www.rfc-editor.org/rfc/rfc9114#section-4.2"

[[exception]]
quote = '''
An intermediary transforming an HTTP/1.x message to HTTP/3 MUST
remove connection-specific header fields as discussed in
Section 7.6.1 of [HTTP], or their messages will be treated by other
HTTP/3 endpoints as malformed.
'''
reason = '''
h3 is not meant to be used for intermediaries.
'''
