target = "https://www.rfc-editor.org/rfc/rfc9114#section-9"

[[exception]]
quote = '''
Extensions that could change the semantics of existing protocol
components MUST be negotiated before being used.
'''
reason = '''
The user should ensure that the order is correct, as h3 does not
handle protocol negotiations.
'''

[[exception]]
quote = '''
If a setting is used for extension negotiation, the default
value MUST be defined in such a fashion that the extension is
disabled if the setting is omitted.
'''
reason = '''
The requirement applies to extension specifications.
'''
