target = "https://www.rfc-editor.org/rfc/rfc9114#section-10.5.1"

[[TODO]]
quote = '''
An endpoint can use the SETTINGS_MAX_FIELD_SECTION_SIZE
(Section 4.2.2) setting to advise peers of limits that might apply on
the size of field sections.  This setting is only advisory, so
endpoints MAY choose to send field sections that exceed this limit
and risk having the request or response being treated as malformed.
'''
