target = "https://www.rfc-editor.org/rfc/rfc9114#section-10.5"

[[TODO]]
quote = '''
A client that accepts server push SHOULD limit the number
of push IDs it issues at a time.
'''

[[TODO]]
quote = '''
All these features -- i.e., server push, unknown protocol elements,
field compression -- have legitimate uses.  These features become a
burden only when they are used unnecessarily or to excess.

An endpoint that does not monitor such behavior exposes itself to a
risk of denial-of-service attack.  Implementations SHOULD track the
use of these features and set limits on their use.
'''

[[TODO]]
quote = '''
An endpoint MAY
treat activity that is suspicious as a connection error of type
H3_EXCESSIVE_LOAD, but false positives will result in disrupting
valid connections and requests.
'''
