target = "https://www.rfc-editor.org/rfc/rfc9114#section-4.2.1"

[[TODO]]
quote = '''
If a decompressed field
section contains multiple cookie field lines, these MUST be
concatenated into a single byte string using the two-byte delimiter
of "; " (ASCII 0x3b, 0x20) before being passed into a context other
than HTTP/2 or HTTP/3, such as an HTTP/1.1 connection, or a generic
HTTP server application.
'''
