target = "https://www.rfc-editor.org/rfc/rfc9114#section-4.2"

[[TODO]]
quote = '''
An endpoint MUST NOT generate
an HTTP/3 field section containing connection-specific fields; any
message containing connection-specific fields MUST be treated as
malformed.
'''

[[TODO]]
quote = '''
The only exception to this is the TE header field, which MAY be
present in an HTTP/3 request header; when it is, it MUST NOT contain
any value other than "trailers".
'''
