target = "https://www.rfc-editor.org/rfc/rfc9114#section-4.3"

[[TODO]]
quote = '''
Endpoints MUST treat a request or response that contains
undefined or invalid pseudo-header fields as malformed.
'''

[[TODO]]
quote = '''
Any request or response that contains a
pseudo-header field that appears in a header section after a regular
header field MUST be treated as malformed.
'''
