target = "https://www.rfc-editor.org/rfc/rfc9114#section-5.3"

[[TODO]]
quote = '''
Before closing the connection, a GOAWAY frame MAY be sent to allow
the client to retry some requests.  Including the GOAWAY frame in the
same packet as the QUIC CONNECTION_CLOSE frame improves the chances
of the frame being received by clients.
'''
