target = "https://www.rfc-editor.org/rfc/rfc9114#section-7.2.8"

[[TODO]]
quote = '''
Endpoints MUST
NOT consider these frames to have any meaning upon receipt.
'''

[[TODO]]
quote = '''
Frame types that were used in HTTP/2 where there is no corresponding
HTTP/3 frame have also been reserved (Section 11.2.1).  These frame
types MUST NOT be sent, and their receipt MUST be treated as a
connection error of type H3_FRAME_UNEXPECTED.
'''
