target = "https://www.rfc-editor.org/rfc/rfc9114#section-8.1"

[[TODO]]
quote = '''
Error codes of the format 0x1f * N + 0x21 for non-negative integer
values of N are reserved to exercise the requirement that unknown
error codes be treated as equivalent to H3_NO_ERROR (Section 9).
Implementations SHOULD select an error code from this space with some
probability when they would have sent H3_NO_ERROR.
'''
