target = "https://www.rfc-editor.org/rfc/rfc9114#section-8"

[[TODO]]
quote = '''
An endpoint MAY choose to treat a stream error as a connection error
under certain circumstances, closing the entire connection in
response to a condition on a single stream.
'''

[[TODO]]
quote = '''
Because new error codes can be defined without negotiation (see
Section 9), use of an error code in an unexpected context or receipt
of an unknown error code MUST be treated as equivalent to
H3_NO_ERROR.
'''
