target = "ci/compliance/specs/rfc9114.txt#10.4"

# 10.4.  Cacheability of Pushed Responses
#
# Pushed responses do not have an explicit request from the client; the
# request is provided by the server in the PUSH_PROMISE frame.
# 
# Caching responses that are pushed is possible based on the guidance
# provided by the origin server in the Cache-Control header field.
# However, this can cause issues if a single server hosts more than one
# tenant.  For example, a server might offer multiple users each a
# small portion of its URI space.
# 
# Where multiple tenants share space on the same server, that server
# MUST ensure that tenants are not able to push representations of
# resources that they do not have authority over.  Failure to enforce
# this would allow a tenant to provide a representation that would be
# served out of cache, overriding the actual representation that the
# authoritative tenant provides.
# 
# Clients are required to reject pushed responses for which an origin
# server is not authoritative; see Section 4.6.

[[spec]]
level = "MUST"
quote = '''
Where multiple tenants share space on the same server, that server
MUST ensure that tenants are not able to push representations of
resources that they do not have authority over.
'''

