target = "ci/compliance/specs/rfc9114.txt#10.5"

# 10.5.  Denial-of-Service Considerations
#
# An HTTP/3 connection can demand a greater commitment of resources to
# operate than an HTTP/1.1 or HTTP/2 connection.  The use of field
# compression and flow control depend on a commitment of resources for
# storing a greater amount of state.  Settings for these features
# ensure that memory commitments for these features are strictly
# bounded.
# 
# The number of PUSH_PROMISE frames is constrained in a similar
# fashion.  A client that accepts server push SHOULD limit the number
# of push IDs it issues at a time.
# 
# Processing capacity cannot be guarded as effectively as state
# capacity.
# 
# The ability to send undefined protocol elements that the peer is
# required to ignore can be abused to cause a peer to expend additional
# processing time.  This might be done by setting multiple undefined
# SETTINGS parameters, unknown frame types, or unknown stream types.
# Note, however, that some uses are entirely legitimate, such as
# optional-to-understand extensions and padding to increase resistance
# to traffic analysis.
# 
# Compression of field sections also offers some opportunities to waste
# processing resources; see Section 7 of [QPACK] for more details on
# potential abuses.
# 
# All these features -- i.e., server push, unknown protocol elements,
# field compression -- have legitimate uses.  These features become a
# burden only when they are used unnecessarily or to excess.
# 
# An endpoint that does not monitor such behavior exposes itself to a
# risk of denial-of-service attack.  Implementations SHOULD track the
# use of these features and set limits on their use.  An endpoint MAY
# treat activity that is suspicious as a connection error of type
# H3_EXCESSIVE_LOAD, but false positives will result in disrupting
# valid connections and requests.

[[spec]]
level = "SHOULD"
quote = '''
A client that accepts server push SHOULD limit the number
of push IDs it issues at a time.
'''

[[spec]]
level = "SHOULD"
quote = '''
Implementations SHOULD track the
use of these features and set limits on their use.
'''

[[spec]]
level = "MAY"
quote = '''
An endpoint MAY
treat activity that is suspicious as a connection error of type
H3_EXCESSIVE_LOAD, but false positives will result in disrupting
valid connections and requests.
'''

