target = "ci/compliance/specs/rfc9114.txt#10.5.1"

# 10.5.1.  Limits on Field Section Size
#
# A large field section (Section 4.1) can cause an implementation to
# commit a large amount of state.  Header fields that are critical for
# routing can appear toward the end of a header section, which prevents
# streaming of the header section to its ultimate destination.  This
# ordering and other reasons, such as ensuring cache correctness, mean
# that an endpoint likely needs to buffer the entire header section.
# Since there is no hard limit to the size of a field section, some
# endpoints could be forced to commit a large amount of available
# memory for header fields.
# 
# An endpoint can use the SETTINGS_MAX_FIELD_SECTION_SIZE
# (Section 4.2.2) setting to advise peers of limits that might apply on
# the size of field sections.  This setting is only advisory, so
# endpoints MAY choose to send field sections that exceed this limit
# and risk having the request or response being treated as malformed.
# This setting is specific to an HTTP/3 connection, so any request or
# response could encounter a hop with a lower, unknown limit.  An
# intermediary can attempt to avoid this problem by passing on values
# presented by different peers, but they are not obligated to do so.
# 
# A server that receives a larger field section than it is willing to
# handle can send an HTTP 431 (Request Header Fields Too Large) status
# code ([RFC6585]).  A client can discard responses that it cannot
# process.

[[spec]]
level = "MAY"
quote = '''
This setting is only advisory, so
endpoints MAY choose to send field sections that exceed this limit
and risk having the request or response being treated as malformed.
'''

