target = "ci/compliance/specs/rfc9114.txt#11.2.4"

# 11.2.4.  Stream Types
#
# This document establishes a registry for HTTP/3 unidirectional stream
# types.  The "HTTP/3 Stream Types" registry governs a 62-bit space.
# This registry follows the QUIC registry policy; see Section 11.2.
# Permanent registrations in this registry are assigned using the
# Specification Required policy ([RFC8126]), except for values between
# 0x00 and 0x3f (in hexadecimal; inclusive), which are assigned using
# Standards Action or IESG Approval as defined in Sections 4.9 and 4.10
# of [RFC8126].
# 
# In addition to common fields as described in Section 11.2, permanent
# registrations in this registry MUST include the following fields:
# 
# Stream Type:  A name or label for the stream type.
# 
# Sender:  Which endpoint on an HTTP/3 connection may initiate a stream
#    of this type.  Values are "Client", "Server", or "Both".
# 
# Specifications for permanent registrations MUST include a description
# of the stream type, including the layout and semantics of the stream
# contents.
# 
# The entries in Table 5 are registered by this document.
# 
#          +================+=======+===============+========+
#          | Stream Type    | Value | Specification | Sender |
#          +================+=======+===============+========+
#          | Control Stream |  0x00 | Section 6.2.1 | Both   |
#          +----------------+-------+---------------+--------+
#          | Push Stream    |  0x01 | Section 4.6   | Server |
#          +----------------+-------+---------------+--------+
# 
#                     Table 5: Initial Stream Types
# 
# Each code of the format 0x1f * N + 0x21 for non-negative integer
# values of N (that is, 0x21, 0x40, ..., through 0x3ffffffffffffffe)
# MUST NOT be assigned by IANA and MUST NOT appear in the listing of
# assigned values.

[[spec]]
level = "MUST"
quote = '''
In addition to common fields as described in Section 11.2, permanent
registrations in this registry MUST include the following fields:
'''

[[spec]]
level = "MUST"
quote = '''
Specifications for permanent registrations MUST include a description
of the stream type, including the layout and semantics of the stream
contents.
'''

[[spec]]
level = "MUST"
quote = '''
Each code of the format 0x1f * N + 0x21 for non-negative integer
values of N (that is, 0x21, 0x40, ..., through 0x3ffffffffffffffe)
MUST NOT be assigned by IANA and MUST NOT appear in the listing of
assigned values.
'''

[[spec]]
level = "MUST"
quote = '''
Each code of the format 0x1f * N + 0x21 for non-negative integer
values of N (that is, 0x21, 0x40, ..., through 0x3ffffffffffffffe)
MUST NOT be assigned by IANA and MUST NOT appear in the listing of
assigned values.
'''

