target = "ci/compliance/specs/rfc9114.txt#3.1"

# 3.1.  Discovering an HTTP/3 Endpoint
#
# HTTP relies on the notion of an authoritative response: a response
# that has been determined to be the most appropriate response for that
# request given the state of the target resource at the time of
# response message origination by (or at the direction of) the origin
# server identified within the target URI.  Locating an authoritative
# server for an HTTP URI is discussed in Section 4.3 of [HTTP].
# 
# The "https" scheme associates authority with possession of a
# certificate that the client considers to be trustworthy for the host
# identified by the authority component of the URI.  Upon receiving a
# server certificate in the TLS handshake, the client MUST verify that
# the certificate is an acceptable match for the URI's origin server
# using the process described in Section 4.3.4 of [HTTP].  If the
# certificate cannot be verified with respect to the URI's origin
# server, the client MUST NOT consider the server authoritative for
# that origin.
# 
# A client MAY attempt access to a resource with an "https" URI by
# resolving the host identifier to an IP address, establishing a QUIC
# connection to that address on the indicated port (including
# validation of the server certificate as described above), and sending
# an HTTP/3 request message targeting the URI to the server over that
# secured connection.  Unless some other mechanism is used to select
# HTTP/3, the token "h3" is used in the Application-Layer Protocol
# Negotiation (ALPN; see [RFC7301]) extension during the TLS handshake.
# 
# Connectivity problems (e.g., blocking UDP) can result in a failure to
# establish a QUIC connection; clients SHOULD attempt to use TCP-based
# versions of HTTP in this case.
# 
# Servers MAY serve HTTP/3 on any UDP port; an alternative service
# advertisement always includes an explicit port, and URIs contain
# either an explicit port or a default port associated with the scheme.

[[spec]]
level = "MUST"
quote = '''
Upon receiving a
server certificate in the TLS handshake, the client MUST verify that
the certificate is an acceptable match for the URI's origin server
using the process described in Section 4.3.4 of [HTTP].
'''

[[spec]]
level = "MUST"
quote = '''
If the
certificate cannot be verified with respect to the URI's origin
server, the client MUST NOT consider the server authoritative for
that origin.
'''

[[spec]]
level = "MAY"
quote = '''
A client MAY attempt access to a resource with an "https" URI by
resolving the host identifier to an IP address, establishing a QUIC
connection to that address on the indicated port (including
validation of the server certificate as described above), and sending
an HTTP/3 request message targeting the URI to the server over that
secured connection.
'''

[[spec]]
level = "SHOULD"
quote = '''
Connectivity problems (e.g., blocking UDP) can result in a failure to
establish a QUIC connection; clients SHOULD attempt to use TCP-based
versions of HTTP in this case.
'''

[[spec]]
level = "MAY"
quote = '''
Servers MAY serve HTTP/3 on any UDP port; an alternative service
advertisement always includes an explicit port, and URIs contain
either an explicit port or a default port associated with the scheme.
'''

