target = "ci/compliance/specs/rfc9114.txt#3.2"

# 3.2.  Connection Establishment
#
# HTTP/3 relies on QUIC version 1 as the underlying transport.  The use
# of other QUIC transport versions with HTTP/3 MAY be defined by future
# specifications.
# 
# QUIC version 1 uses TLS version 1.3 or greater as its handshake
# protocol.  HTTP/3 clients MUST support a mechanism to indicate the
# target host to the server during the TLS handshake.  If the server is
# identified by a domain name ([DNS-TERMS]), clients MUST send the
# Server Name Indication (SNI; [RFC6066]) TLS extension unless an
# alternative mechanism to indicate the target host is used.
# 
# QUIC connections are established as described in [QUIC-TRANSPORT].
# During connection establishment, HTTP/3 support is indicated by
# selecting the ALPN token "h3" in the TLS handshake.  Support for
# other application-layer protocols MAY be offered in the same
# handshake.
# 
# While connection-level options pertaining to the core QUIC protocol
# are set in the initial crypto handshake, settings specific to HTTP/3
# are conveyed in the SETTINGS frame.  After the QUIC connection is
# established, a SETTINGS frame MUST be sent by each endpoint as the
# initial frame of their respective HTTP control stream.

[[spec]]
level = "MAY"
quote = '''
The use
of other QUIC transport versions with HTTP/3 MAY be defined by future
specifications.
'''

[[spec]]
level = "MUST"
quote = '''
HTTP/3 clients MUST support a mechanism to indicate the
target host to the server during the TLS handshake.
'''

[[spec]]
level = "MUST"
quote = '''
If the server is
identified by a domain name ([DNS-TERMS]), clients MUST send the
Server Name Indication (SNI; [RFC6066]) TLS extension unless an
alternative mechanism to indicate the target host is used.
'''

[[spec]]
level = "MAY"
quote = '''
Support for
other application-layer protocols MAY be offered in the same
handshake.
'''

[[spec]]
level = "MUST"
quote = '''
After the QUIC connection is
established, a SETTINGS frame MUST be sent by each endpoint as the
initial frame of their respective HTTP control stream.
'''

