target = "ci/compliance/specs/rfc9114.txt#3.3"

# 3.3.  Connection Reuse
#
# HTTP/3 connections are persistent across multiple requests.  For best
# performance, it is expected that clients will not close connections
# until it is determined that no further communication with a server is
# necessary (for example, when a user navigates away from a particular
# web page) or until the server closes the connection.
# 
# Once a connection to a server endpoint exists, this connection MAY be
# reused for requests with multiple different URI authority components.
# To use an existing connection for a new origin, clients MUST validate
# the certificate presented by the server for the new origin server
# using the process described in Section 4.3.4 of [HTTP].  This implies
# that clients will need to retain the server certificate and any
# additional information needed to verify that certificate; clients
# that do not do so will be unable to reuse the connection for
# additional origins.
# 
# If the certificate is not acceptable with regard to the new origin
# for any reason, the connection MUST NOT be reused and a new
# connection SHOULD be established for the new origin.  If the reason
# the certificate cannot be verified might apply to other origins
# already associated with the connection, the client SHOULD revalidate
# the server certificate for those origins.  For instance, if
# validation of a certificate fails because the certificate has expired
# or been revoked, this might be used to invalidate all other origins
# for which that certificate was used to establish authority.
# 
# Clients SHOULD NOT open more than one HTTP/3 connection to a given IP
# address and UDP port, where the IP address and port might be derived
# from a URI, a selected alternative service ([ALTSVC]), a configured
# proxy, or name resolution of any of these.  A client MAY open
# multiple HTTP/3 connections to the same IP address and UDP port using
# different transport or TLS configurations but SHOULD avoid creating
# multiple connections with the same configuration.
# 
# Servers are encouraged to maintain open HTTP/3 connections for as
# long as possible but are permitted to terminate idle connections if
# necessary.  When either endpoint chooses to close the HTTP/3
# connection, the terminating endpoint SHOULD first send a GOAWAY frame
# (Section 5.2) so that both endpoints can reliably determine whether
# previously sent frames have been processed and gracefully complete or
# terminate any necessary remaining tasks.
# 
# A server that does not wish clients to reuse HTTP/3 connections for a
# particular origin can indicate that it is not authoritative for a
# request by sending a 421 (Misdirected Request) status code in
# response to the request; see Section 7.4 of [HTTP].

[[spec]]
level = "MAY"
quote = '''
Once a connection to a server endpoint exists, this connection MAY be
reused for requests with multiple different URI authority components.
'''

[[spec]]
level = "MUST"
quote = '''
To use an existing connection for a new origin, clients MUST validate
the certificate presented by the server for the new origin server
using the process described in Section 4.3.4 of [HTTP].
'''

[[spec]]
level = "MUST"
quote = '''
If the certificate is not acceptable with regard to the new origin
for any reason, the connection MUST NOT be reused and a new
connection SHOULD be established for the new origin.
'''

[[spec]]
level = "SHOULD"
quote = '''
If the reason
the certificate cannot be verified might apply to other origins
already associated with the connection, the client SHOULD revalidate
the server certificate for those origins.
'''

[[spec]]
level = "SHOULD"
quote = '''
Clients SHOULD NOT open more than one HTTP/3 connection to a given IP
address and UDP port, where the IP address and port might be derived
from a URI, a selected alternative service ([ALTSVC]), a configured
proxy, or name resolution of any of these.
'''

[[spec]]
level = "SHOULD"
quote = '''
A client MAY open
multiple HTTP/3 connections to the same IP address and UDP port using
different transport or TLS configurations but SHOULD avoid creating
multiple connections with the same configuration.
'''

[[spec]]
level = "SHOULD"
quote = '''
When either endpoint chooses to close the HTTP/3
connection, the terminating endpoint SHOULD first send a GOAWAY frame
(Section 5.2) so that both endpoints can reliably determine whether
previously sent frames have been processed and gracefully complete or
terminate any necessary remaining tasks.
'''

