target = "ci/compliance/specs/rfc9114.txt#4.2"

# 4.2.  HTTP Fields
#
# HTTP messages carry metadata as a series of key-value pairs called
# "HTTP fields"; see Sections 6.3 and 6.5 of [HTTP].  For a listing of
# registered HTTP fields, see the "Hypertext Transfer Protocol (HTTP)
# Field Name Registry" maintained at <https://www.iana.org/assignments/
# http-fields/>.  Like HTTP/2, HTTP/3 has additional considerations
# related to the use of characters in field names, the Connection
# header field, and pseudo-header fields.
# 
# Field names are strings containing a subset of ASCII characters.
# Properties of HTTP field names and values are discussed in more
# detail in Section 5.1 of [HTTP].  Characters in field names MUST be
# converted to lowercase prior to their encoding.  A request or
# response containing uppercase characters in field names MUST be
# treated as malformed.
# 
# HTTP/3 does not use the Connection header field to indicate
# connection-specific fields; in this protocol, connection-specific
# metadata is conveyed by other means.  An endpoint MUST NOT generate
# an HTTP/3 field section containing connection-specific fields; any
# message containing connection-specific fields MUST be treated as
# malformed.
# 
# The only exception to this is the TE header field, which MAY be
# present in an HTTP/3 request header; when it is, it MUST NOT contain
# any value other than "trailers".
# 
# An intermediary transforming an HTTP/1.x message to HTTP/3 MUST
# remove connection-specific header fields as discussed in
# Section 7.6.1 of [HTTP], or their messages will be treated by other
# HTTP/3 endpoints as malformed.

[[spec]]
level = "MUST"
quote = '''
Characters in field names MUST be
converted to lowercase prior to their encoding.
'''

[[spec]]
level = "MUST"
quote = '''
A request or
response containing uppercase characters in field names MUST be
treated as malformed.
'''

[[spec]]
level = "MUST"
quote = '''
An endpoint MUST NOT generate
an HTTP/3 field section containing connection-specific fields; any
message containing connection-specific fields MUST be treated as
malformed.
'''

[[spec]]
level = "MUST"
quote = '''
An endpoint MUST NOT generate
an HTTP/3 field section containing connection-specific fields; any
message containing connection-specific fields MUST be treated as
malformed.
'''

[[spec]]
level = "MUST"
quote = '''
The only exception to this is the TE header field, which MAY be
present in an HTTP/3 request header; when it is, it MUST NOT contain
any value other than "trailers".
'''

[[spec]]
level = "MUST"
quote = '''
An intermediary transforming an HTTP/1.x message to HTTP/3 MUST
remove connection-specific header fields as discussed in
Section 7.6.1 of [HTTP], or their messages will be treated by other
HTTP/3 endpoints as malformed.
'''

