target = "ci/compliance/specs/rfc9114.txt#4.3.1"

# 4.3.1.  Request Pseudo-Header Fields
#
# The following pseudo-header fields are defined for requests:
# 
# ":method":  Contains the HTTP method (Section 9 of [HTTP])
# 
# ":scheme":  Contains the scheme portion of the target URI
#    (Section 3.1 of [URI]).
# 
#    The :scheme pseudo-header is not restricted to URIs with scheme
#    "http" and "https".  A proxy or gateway can translate requests for
#    non-HTTP schemes, enabling the use of HTTP to interact with non-
#    HTTP services.
# 
#    See Section 3.1.2 for guidance on using a scheme other than
#    "https".
# 
# ":authority":  Contains the authority portion of the target URI
#    (Section 3.2 of [URI]).  The authority MUST NOT include the
#    deprecated userinfo subcomponent for URIs of scheme "http" or
#    "https".
# 
#    To ensure that the HTTP/1.1 request line can be reproduced
#    accurately, this pseudo-header field MUST be omitted when
#    translating from an HTTP/1.1 request that has a request target in
#    a method-specific form; see Section 7.1 of [HTTP].  Clients that
#    generate HTTP/3 requests directly SHOULD use the :authority
#    pseudo-header field instead of the Host header field.  An
#    intermediary that converts an HTTP/3 request to HTTP/1.1 MUST
#    create a Host field if one is not present in a request by copying
#    the value of the :authority pseudo-header field.
# 
# ":path":  Contains the path and query parts of the target URI (the
#    "path-absolute" production and optionally a ? character (ASCII
#    0x3f) followed by the "query" production; see Sections 3.3 and 3.4
#    of [URI].
# 
#    This pseudo-header field MUST NOT be empty for "http" or "https"
#    URIs; "http" or "https" URIs that do not contain a path component
#    MUST include a value of / (ASCII 0x2f).  An OPTIONS request that
#    does not include a path component includes the value * (ASCII
#    0x2a) for the :path pseudo-header field; see Section 7.1 of
#    [HTTP].
# 
# All HTTP/3 requests MUST include exactly one value for the :method,
# :scheme, and :path pseudo-header fields, unless the request is a
# CONNECT request; see Section 4.4.
# 
# If the :scheme pseudo-header field identifies a scheme that has a
# mandatory authority component (including "http" and "https"), the
# request MUST contain either an :authority pseudo-header field or a
# Host header field.  If these fields are present, they MUST NOT be
# empty.  If both fields are present, they MUST contain the same value.
# If the scheme does not have a mandatory authority component and none
# is provided in the request target, the request MUST NOT contain the
# :authority pseudo-header or Host header fields.
# 
# An HTTP request that omits mandatory pseudo-header fields or contains
# invalid values for those pseudo-header fields is malformed.
# 
# HTTP/3 does not define a way to carry the version identifier that is
# included in the HTTP/1.1 request line.  HTTP/3 requests implicitly
# have a protocol version of "3.0".

[[spec]]
level = "MUST"
quote = '''
The authority MUST NOT include the
deprecated userinfo subcomponent for URIs of scheme "http" or
"https".
'''

[[spec]]
level = "MUST"
quote = '''
To ensure that the HTTP/1.1 request line can be reproduced
accurately, this pseudo-header field MUST be omitted when
translating from an HTTP/1.1 request that has a request target in
a method-specific form; see Section 7.1 of [HTTP].
'''

[[spec]]
level = "SHOULD"
quote = '''
Clients that
generate HTTP/3 requests directly SHOULD use the :authority
pseudo-header field instead of the Host header field.
'''

[[spec]]
level = "MUST"
quote = '''
An
intermediary that converts an HTTP/3 request to HTTP/1.1 MUST
create a Host field if one is not present in a request by copying
the value of the :authority pseudo-header field.
'''

[[spec]]
level = "MUST"
quote = '''
This pseudo-header field MUST NOT be empty for "http" or "https"
URIs; "http" or "https" URIs that do not contain a path component
MUST include a value of / (ASCII 0x2f).
'''

[[spec]]
level = "MUST"
quote = '''
This pseudo-header field MUST NOT be empty for "http" or "https"
URIs; "http" or "https" URIs that do not contain a path component
MUST include a value of / (ASCII 0x2f).
'''

[[spec]]
level = "MUST"
quote = '''
All HTTP/3 requests MUST include exactly one value for the :method,
:scheme, and :path pseudo-header fields, unless the request is a
CONNECT request; see Section 4.4.
'''

[[spec]]
level = "MUST"
quote = '''
If the :scheme pseudo-header field identifies a scheme that has a
mandatory authority component (including "http" and "https"), the
request MUST contain either an :authority pseudo-header field or a
Host header field.
'''

[[spec]]
level = "MUST"
quote = '''
If these fields are present, they MUST NOT be
empty.
'''

[[spec]]
level = "MUST"
quote = '''
If both fields are present, they MUST contain the same value.
'''

[[spec]]
level = "MUST"
quote = '''
If the scheme does not have a mandatory authority component and none
is provided in the request target, the request MUST NOT contain the
:authority pseudo-header or Host header fields.
'''

