target = "ci/compliance/specs/rfc9114.txt#4.4"

# 4.4.  The CONNECT Method
#
# The CONNECT method requests that the recipient establish a tunnel to
# the destination origin server identified by the request-target; see
# Section 9.3.6 of [HTTP].  It is primarily used with HTTP proxies to
# establish a TLS session with an origin server for the purposes of
# interacting with "https" resources.
# 
# In HTTP/1.x, CONNECT is used to convert an entire HTTP connection
# into a tunnel to a remote host.  In HTTP/2 and HTTP/3, the CONNECT
# method is used to establish a tunnel over a single stream.
# 
# A CONNECT request MUST be constructed as follows:
# 
# *  The :method pseudo-header field is set to "CONNECT"
# 
# *  The :scheme and :path pseudo-header fields are omitted
# 
# *  The :authority pseudo-header field contains the host and port to
#    connect to (equivalent to the authority-form of the request-target
#    of CONNECT requests; see Section 7.1 of [HTTP]).
# 
# The request stream remains open at the end of the request to carry
# the data to be transferred.  A CONNECT request that does not conform
# to these restrictions is malformed.
# 
# A proxy that supports CONNECT establishes a TCP connection
# ([RFC0793]) to the server identified in the :authority pseudo-header
# field.  Once this connection is successfully established, the proxy
# sends a HEADERS frame containing a 2xx series status code to the
# client, as defined in Section 15.3 of [HTTP].
# 
# All DATA frames on the stream correspond to data sent or received on
# the TCP connection.  The payload of any DATA frame sent by the client
# is transmitted by the proxy to the TCP server; data received from the
# TCP server is packaged into DATA frames by the proxy.  Note that the
# size and number of TCP segments is not guaranteed to map predictably
# to the size and number of HTTP DATA or QUIC STREAM frames.
# 
# Once the CONNECT method has completed, only DATA frames are permitted
# to be sent on the stream.  Extension frames MAY be used if
# specifically permitted by the definition of the extension.  Receipt
# of any other known frame type MUST be treated as a connection error
# of type H3_FRAME_UNEXPECTED.
# 
# The TCP connection can be closed by either peer.  When the client
# ends the request stream (that is, the receive stream at the proxy
# enters the "Data Recvd" state), the proxy will set the FIN bit on its
# connection to the TCP server.  When the proxy receives a packet with
# the FIN bit set, it will close the send stream that it sends to the
# client.  TCP connections that remain half closed in a single
# direction are not invalid, but are often handled poorly by servers,
# so clients SHOULD NOT close a stream for sending while they still
# expect to receive data from the target of the CONNECT.
# 
# A TCP connection error is signaled by abruptly terminating the
# stream.  A proxy treats any error in the TCP connection, which
# includes receiving a TCP segment with the RST bit set, as a stream
# error of type H3_CONNECT_ERROR.
# 
# Correspondingly, if a proxy detects an error with the stream or the
# QUIC connection, it MUST close the TCP connection.  If the proxy
# detects that the client has reset the stream or aborted reading from
# the stream, it MUST close the TCP connection.  If the stream is reset
# or reading is aborted by the client, a proxy SHOULD perform the same
# operation on the other direction in order to ensure that both
# directions of the stream are cancelled.  In all these cases, if the
# underlying TCP implementation permits it, the proxy SHOULD send a TCP
# segment with the RST bit set.
# 
# Since CONNECT creates a tunnel to an arbitrary server, proxies that
# support CONNECT SHOULD restrict its use to a set of known ports or a
# list of safe request targets; see Section 9.3.6 of [HTTP] for more
# details.

[[spec]]
level = "MUST"
quote = '''
A CONNECT request MUST be constructed as follows:
'''

[[spec]]
level = "MAY"
quote = '''
Extension frames MAY be used if
specifically permitted by the definition of the extension.
'''

[[spec]]
level = "MUST"
quote = '''
Receipt
of any other known frame type MUST be treated as a connection error
of type H3_FRAME_UNEXPECTED.
'''

[[spec]]
level = "SHOULD"
quote = '''
TCP connections that remain half closed in a single
direction are not invalid, but are often handled poorly by servers,
so clients SHOULD NOT close a stream for sending while they still
expect to receive data from the target of the CONNECT.
'''

[[spec]]
level = "MUST"
quote = '''
Correspondingly, if a proxy detects an error with the stream or the
QUIC connection, it MUST close the TCP connection.
'''

[[spec]]
level = "MUST"
quote = '''
If the proxy
detects that the client has reset the stream or aborted reading from
the stream, it MUST close the TCP connection.
'''

[[spec]]
level = "SHOULD"
quote = '''
If the stream is reset
or reading is aborted by the client, a proxy SHOULD perform the same
operation on the other direction in order to ensure that both
directions of the stream are cancelled.
'''

[[spec]]
level = "SHOULD"
quote = '''
In all these cases, if the
underlying TCP implementation permits it, the proxy SHOULD send a TCP
segment with the RST bit set.
'''

[[spec]]
level = "SHOULD"
quote = '''
Since CONNECT creates a tunnel to an arbitrary server, proxies that
support CONNECT SHOULD restrict its use to a set of known ports or a
list of safe request targets; see Section 9.3.6 of [HTTP] for more
details.
'''

