target = "ci/compliance/specs/rfc9114.txt#5.3"

# 5.3.  Immediate Application Closure
#
# An HTTP/3 implementation can immediately close the QUIC connection at
# any time.  This results in sending a QUIC CONNECTION_CLOSE frame to
# the peer indicating that the application layer has terminated the
# connection.  The application error code in this frame indicates to
# the peer why the connection is being closed.  See Section 8 for error
# codes that can be used when closing a connection in HTTP/3.
# 
# Before closing the connection, a GOAWAY frame MAY be sent to allow
# the client to retry some requests.  Including the GOAWAY frame in the
# same packet as the QUIC CONNECTION_CLOSE frame improves the chances
# of the frame being received by clients.
# 
# If there are open streams that have not been explicitly closed, they
# are implicitly closed when the connection is closed; see Section 10.2
# of [QUIC-TRANSPORT].

[[spec]]
level = "MAY"
quote = '''
Before closing the connection, a GOAWAY frame MAY be sent to allow
the client to retry some requests.
'''

