target = "ci/compliance/specs/rfc9114.txt#5.4"

# 5.4.  Transport Closure
#
# For various reasons, the QUIC transport could indicate to the
# application layer that the connection has terminated.  This might be
# due to an explicit closure by the peer, a transport-level error, or a
# change in network topology that interrupts connectivity.
# 
# If a connection terminates without a GOAWAY frame, clients MUST
# assume that any request that was sent, whether in whole or in part,
# might have been processed.

[[spec]]
level = "MUST"
quote = '''
If a connection terminates without a GOAWAY frame, clients MUST
assume that any request that was sent, whether in whole or in part,
might have been processed.
'''

