target = "ci/compliance/specs/rfc9114.txt#7.2.5"

# 7.2.5.  PUSH_PROMISE
#
# The PUSH_PROMISE frame (type=0x05) is used to carry a promised
# request header section from server to client on a request stream.
# 
# PUSH_PROMISE Frame {
#   Type (i) = 0x05,
#   Length (i),
#   Push ID (i),
#   Encoded Field Section (..),
# }
# 
#                      Figure 8: PUSH_PROMISE Frame
# 
# The payload consists of:
# 
# Push ID:  A variable-length integer that identifies the server push
#    operation.  A push ID is used in push stream headers (Section 4.6)
#    and CANCEL_PUSH frames.
# 
# Encoded Field Section:  QPACK-encoded request header fields for the
#    promised response.  See [QPACK] for more details.
# 
# A server MUST NOT use a push ID that is larger than the client has
# provided in a MAX_PUSH_ID frame (Section 7.2.7).  A client MUST treat
# receipt of a PUSH_PROMISE frame that contains a larger push ID than
# the client has advertised as a connection error of H3_ID_ERROR.
# 
# A server MAY use the same push ID in multiple PUSH_PROMISE frames.
# If so, the decompressed request header sets MUST contain the same
# fields in the same order, and both the name and the value in each
# field MUST be exact matches.  Clients SHOULD compare the request
# header sections for resources promised multiple times.  If a client
# receives a push ID that has already been promised and detects a
# mismatch, it MUST respond with a connection error of type
# H3_GENERAL_PROTOCOL_ERROR.  If the decompressed field sections match
# exactly, the client SHOULD associate the pushed content with each
# stream on which a PUSH_PROMISE frame was received.
# 
# Allowing duplicate references to the same push ID is primarily to
# reduce duplication caused by concurrent requests.  A server SHOULD
# avoid reusing a push ID over a long period.  Clients are likely to
# consume server push responses and not retain them for reuse over
# time.  Clients that see a PUSH_PROMISE frame that uses a push ID that
# they have already consumed and discarded are forced to ignore the
# promise.
# 
# If a PUSH_PROMISE frame is received on the control stream, the client
# MUST respond with a connection error of type H3_FRAME_UNEXPECTED.
# 
# A client MUST NOT send a PUSH_PROMISE frame.  A server MUST treat the
# receipt of a PUSH_PROMISE frame as a connection error of type
# H3_FRAME_UNEXPECTED.
# 
# See Section 4.6 for a description of the overall server push
# mechanism.

[[spec]]
level = "MUST"
quote = '''
A server MUST NOT use a push ID that is larger than the client has
provided in a MAX_PUSH_ID frame (Section 7.2.7).
'''

[[spec]]
level = "MUST"
quote = '''
A client MUST treat
receipt of a PUSH_PROMISE frame that contains a larger push ID than
the client has advertised as a connection error of H3_ID_ERROR.
'''

[[spec]]
level = "MAY"
quote = '''
A server MAY use the same push ID in multiple PUSH_PROMISE frames.
'''

[[spec]]
level = "MUST"
quote = '''
If so, the decompressed request header sets MUST contain the same
fields in the same order, and both the name and the value in each
field MUST be exact matches.
'''

[[spec]]
level = "MUST"
quote = '''
If so, the decompressed request header sets MUST contain the same
fields in the same order, and both the name and the value in each
field MUST be exact matches.
'''

[[spec]]
level = "SHOULD"
quote = '''
Clients SHOULD compare the request
header sections for resources promised multiple times.
'''

[[spec]]
level = "MUST"
quote = '''
If a client
receives a push ID that has already been promised and detects a
mismatch, it MUST respond with a connection error of type
H3_GENERAL_PROTOCOL_ERROR.
'''

[[spec]]
level = "SHOULD"
quote = '''
If the decompressed field sections match
exactly, the client SHOULD associate the pushed content with each
stream on which a PUSH_PROMISE frame was received.
'''

[[spec]]
level = "SHOULD"
quote = '''
A server SHOULD
avoid reusing a push ID over a long period.
'''

[[spec]]
level = "MUST"
quote = '''
If a PUSH_PROMISE frame is received on the control stream, the client
MUST respond with a connection error of type H3_FRAME_UNEXPECTED.
'''

[[spec]]
level = "MUST"
quote = '''
A client MUST NOT send a PUSH_PROMISE frame.
'''

[[spec]]
level = "MUST"
quote = '''
A server MUST treat the
receipt of a PUSH_PROMISE frame as a connection error of type
H3_FRAME_UNEXPECTED.
'''

