target = "https://www.rfc-editor.org/rfc/rfc9114#section-10.6"

[[exception]]
quote = '''
Implementations communicating on a secure channel MUST NOT compress
content that includes both confidential and attacker-controlled data
unless separate compression contexts are used for each source of
data.
'''
reason = '''
This should be enforced by the user, as h3 may not be able to
determine the nature of the content.
'''

[[exception]]
quote = '''
Compression MUST NOT be used if the source of data cannot be
reliably determined.
'''
reason = '''
This is up to the user to decide.
'''
