target = "https://www.rfc-editor.org/rfc/rfc9114#section-6.2"

[[exception]]
quote = '''
Each endpoint needs to create at least one unidirectional stream for
the HTTP control stream.  QPACK requires two additional
unidirectional streams, and other extensions might require further
streams.  Therefore, the transport parameters sent by both clients
and servers MUST allow the peer to create at least three
unidirectional streams.  These transport parameters SHOULD also
provide at least 1,024 bytes of flow-control credit to each
unidirectional stream.
'''
reason = '''
The user should ensure that the transport parameters satisfy the
requirements, as h3 does not handle connection establishment.
'''
